name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'

    - name: Upgrade pip and nox
      run: |
        pip install --upgrade pip nox
        pip --version
        nox --version

    - name: Build package
      run: nox -s build

    - name: Upload package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
